/*
ScriptRuntimeException can be caught and thrown by the script. For example, accessing or assigning an undeclared variable is a 
runtime error. However, lexer, parser, and compiler exceptions cannot be caught.
 */
try {
    foo = 22;
} catch(e) {
    console.error(`Caught exception: ${e}`);
}

try {
    let foo = [1, 2];
    console.log(foo[2]);
} catch(e) {
    console.error(e);
}

try {
    throw "it back";
    console.log("Didn't throw");
} finally {
    console.log("Always do this");
}

// As of Feb 18 15:30 2021 This program runs as intended.